<a href="https://colab.research.google.com/github/nishtha-09-gupta/AirbnbDATAanalysis/blob/main/notebooks/A2_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

In [13]:
df=pd.read_csv("Airbnb_Open_Data.csv",low_memory=False)

In [14]:
df.isnull().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(541)

In [16]:
df = df.drop_duplicates()

In [17]:
df.drop(columns=['license'], inplace=True)

In [18]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ','_')
)

In [19]:
df['price'].head()

0    $966
1    $142
2    $620
3    $368
4    $204
Name: price, dtype: object

In [20]:
df['price'] = (
    df['price']
      .str.replace('$','',regex=False)
      .str.replace(',','',regex=False)
      .astype(float)
)

df['service_fee'] = (
    df['service_fee']
      .str.replace('$','',regex=False)
      .str.replace(',','',regex=False)
      .astype(float)
)

In [21]:
df['last_review'] = pd.to_datetime(
    df['last_review'],
    errors='coerce'
)

In [22]:
nulls = (
    df.isnull().sum()
      .sort_values(ascending=False)
)

In [23]:
df['house_rules'] = df['house_rules'].fillna('Not Provided')

In [24]:
df['host_identity_verified'] = (
    df['host_identity_verified']
      .fillna('unconfirmed')
)

In [25]:
df['country'].value_counts()

country
United States    101526
Name: count, dtype: int64

In [26]:
df['country'] = (
    df['country']
      .fillna('United States')
)

In [30]:
# df[df['minimum_nights'] < 0]

In [31]:
df = df[df['minimum_nights'] >= 0]

In [33]:
df = df[
    (df['availability_365'] >= 0) &
    (df['availability_365'] <= 365)
]

In [36]:
df['neighbourhood_group'] = (
    df['neighbourhood_group']
      .str.strip()
      .str.title()
)

In [37]:
df['reviews_per_month'] = (
    df['reviews_per_month']
      .fillna(df['reviews_per_month'].median())
)

In [38]:
df.describe()

,id,host_id,lat,long,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
count,9.805700e+04,9.805700e+04,98049.000000,98049.000000,97891.000000,97822.000000,97795.000000,98057.000000,97931.000000,83143,98057.000000,97779.000000,97767.000000,98057.000000
mean,2.981992e+07,4.925044e+10,40.727980,-73.949341,2012.490556,625.857282,125.142748,8.147567,27.183231,2019-06-25 04:57:31.961079296,1.293741,3.286871,8.055510,134.418298
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,50.000000,10.000000,1.000000,0.000000,2012-07-11 00:00:00,0.010000,1.000000,1.000000,0.000000
25%,1.620671e+07,2.456725e+10,40.688680,-73.982510,2008.000000,340.000000,68.000000,2.000000,1.000000,2018-11-08 00:00:00,0.290000,2.000000,1.000000,2.000000
50%,2.995898e+07,4.911989e+10,40.722160,-73.954320,2012.000000,626.000000,125.000000,3.000000,7.000000,2019-06-15 00:00:00,0.760000,3.000000,1.000000,90.000000
75%,4.354721e+07,7.398276e+10,40.762690,-73.931910,2017.000000,913.000000,183.000000,5.000000,30.000000,2019-07-06 00:00:00,1.740000,4.000000,2.000000,254.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,1200.000000,240.000000,5645.000000,1024.000000,2058-06-16 00:00:00,90.000000,5.000000,332.000000,365.000000
std,1.599170e+07,2.854288e+10,0.055971,0.049861,5.764045,331.706499,66.333950,28.653840,48.918785,NaN,1.632960,1.279480,32.671494,129.815853

In [39]:
df.isnull().sum()

id                                    0
name                                217
host_id                               0
host_identity_verified                0
host_name                           385
neighbourhood_group                  16
neighbourhood                        12
lat                                   8
long                                  8
country                               0
country_code                        100
instant_bookable                     74
cancellation_policy                  56
room_type                             0
construction_year                   166
price                               235
service_fee                         262
minimum_nights                        0
number_of_reviews                   126
last_review                       14914
reviews_per_month                     0
review_rate_number                  278
calculated_host_listings_count      290
availability_365                      0
house_rules                           0
dtype: int64

In [40]:
df.to_csv(
    'Airbnb_Cleaned.csv',
    index=False
)